FROM golang:1.16-buster

RUN go get github.com/go-delve/delve/cmd/dlv
RUN mkdir /.cache && chmod -R 777 /.cache
# Add /go/bin to PATH
ENV PATH="/go/bin:${PATH}" 
### Run the Delve debugger ###
COPY /src /src
ENTRYPOINT dlv debug --headless --log-output=debugger --log -l 0.0.0.0:2345 --api-version=2 cmd/main.go
